### ISSUE TITLE
Welcome Activity

### ISSUE THREAD

**Issue by bostwick** [climbhigher/climbhigher-android#1]
As a user who has just installed the application,
I want to be greeted with a friendly welcome screen,
So that I can choose the correct account action.

**Use Cases**
- [x] Given no user has logged into the application, when I open the application, I should be on the Welcome activity. (Issue #12)
- [x] Given I am on the Welcome activity, when the activity launches, I should see the application title, tagline, login button, and registration button. (Issue #13)
- [ ] Given I am on the Welcome activity, when I press the "Login" button, I should go to the Login activity. (Issue #14)
- [ ] Given I am on the Welcome activity, when I press the "Register" button, I should go to the Register activity. (Issue #15)

**Tasks**
- [x] Create the `activity_welcome` layout file for the portrait orientation. (Issue #16)
- [x] Create the WelcomeActivity class. (Issue #17)
- [ ] Add click handler for the login button (Issue #18)
- [ ] Add click handler for the registration button (Issue #19)
