### ISSUE TITLE
Login Activity

### ISSUE THREAD

**Issue by bostwick** [climbhigher/climbhigher-android#2]
As a user who has just installed ClimbHigher,
and already has a Climb Higher account,
I want to log in to my existing account,
So that I can access my climbing sessions.

**Use Cases**
- [ ] Given that I am on the Login Activity, I should see inputs for an email, a password, and a button to log in.
- [ ] Given that I am on the Login Activity, when I press the "Login" button, a modal spinner should appear until the server has returned a response.
- [ ] Given that I am on the Login Activity, when I press the "Login" button and my credentials are valid, I should go to the Main Activity and see my climbing sessions.
- [ ] Given that I am on the Login Activity, when I press the "Login" button and my credentials are invalid, a red error message should appear below the login button.

**Tasks**
- [ ] Create the `activity_login` layout file for the portrait orientation. 
- [ ] Create a LoginActivity class.
- [ ] Add a click handler for the Login button.
- [ ] Add the service call to the user profile api endpoint.
